
export const NUVEI_ENV ={
 APP_CODE : 'SDKHIBRIDOTEST-EC-CLIENT',
 APP_KEY :'jpHQNgutccQQ0uHuzme2ctfol1neBy',
 SERVER_CODE : 'SDKHIBRIDOTEST-EC-SERVER',
 SERVER_KEY : 'QWST19ajwUPLH3YdMP6saPruJZzNwJ',
}